gantt
    title Convergent Evolution of Empirical Scientific Practice toward STAMPED
    dateFormat YYYY
    axisFormat %Y
    tickInterval 5year

    section Foundational Ideas
        Claerbout [S,T,A]                       :milestone, 1992, 0d
        Buckheit/Donoho [S,A,P,D]               :milestone, 1995, 0d
        Gentleman/Temple Lang [S,M,A,D]         :milestone, 2007, 0d
        Noble [S,M]                             :milestone, 2009, 0d

    section Normative Frameworks
        Stodden [D,T]                           :milestone, 2010, 0d
        Sandve et al. [T,A,S]                   :milestone, 2013, 0d
        FAIR Principles                         :milestone, 2016, 0d
        Wilson et al. [A,T,S]                   :milestone, 2017, 0d
        YODA Principles [S,T,M,P,D]             :milestone, 2018, 0d
        De Smedt et al. [A]                     :milestone, 2020, 0d
        VAMP [S,T,A,M,P,E]                      :milestone, 2023, 0d
        WCI-FW                                  :milestone, 2025, 0d

    section Git for Data Tools
        git-annex [T,P,D]                       :milestone, 2010, 0d
        Pachyderm [T,A]                         :milestone, 2014, 0d
        Git LFS [T,D]                           :milestone, 2015, 0d
        DVC [T,A,P]                             :milestone, 2017, 0d
        Icechunk [T,E]                          :milestone, 2024, 0d

    section Platforms and Standards
        Galaxy [A,S]                            :milestone, 2005, 0d
        Frictionless Data [M,P]                 :milestone, 2007, 0d
        W3C PROV [T]                            :milestone, 2013, 0d
        Code Ocean [S,A,E]                      :milestone, 2017, 0d
        brainlife.io [A,D]                      :milestone, 2017, 0d
        RO-Crate [S,M,D]                        :milestone, 2019, 0d
        BioComputeObject [S,T,P]                :milestone, 2020, 0d

    section Framework Tooling
        Cookiecutter DS [S,M]                   :milestone, 2016, 0d
        BIDS [S,M,P]                            :milestone, 2016, 0d
        Kedro [S,A,M]                           :milestone, 2019, 0d
        nipoppy [S,T,M]                         :milestone, 2023, 0d
